name: Generate API Client
on:
  push:
    branches:
        - '*'

permissions:
  contents: write

jobs:
  generate-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout API Admin Repository
        uses: actions/checkout@v4
        with:
          repository: 'NestboxAI/nestbox-ai-dashboard-api'
          ref: 'dev'
          path: 'nestbox-ai-dashboard-api'
          token: ${{ secrets.GH_PAT }}

      - name: Checkout API Documents Repository
        uses: actions/checkout@v4
        with:
          repository: 'NestboxAI/nestbox-ai-document-base'
          ref: 'dev'
          path: 'nestbox-ai-document-base'
          token: ${{ secrets.GH_PAT }}

      - name: Generate Swagger Spec
        run: |
            cd nestbox-ai-dashboard-api
            yarn install
            yarn build
            npm run generate:swagger
            cp nestbox-ai-admin.json ../nestbox-ai-admin.json

      - name: Generate Swagger Spec
        run: |
            cd nestbox-ai-document-base
            yarn install
            yarn build
            npm run generate:swagger
            cp nestbox-ai-documents.json ../nestbox-ai-documents.json

      - name: Remove API Repositories
        run: rm -rf nestbox-ai-dashboard-api nestbox-ai-document-base

      - name: Install OpenAPI Generator CLI
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Validate OpenAPI Spec
        run: openapi-generator-cli validate -i nestbox-ai-admin.json

      - name: Generate API Admin Client
        run: |
          openapi-generator-cli generate \
            -i nestbox-ai-admin.json \
            -g typescript-axios \
            -o admin-client \
            --skip-validate-spec \
            --additional-properties=supportsES6=true,npmName=@nestbox-ai/admin,npmVersion=1.0.${{ github.run_number }},repositoryUrl=https://github.com/NestboxAI/nestbox-ai-clients.git

      - name: Generate API Documents Client
        run: |
          openapi-generator-cli generate \
            -i nestbox-ai-documents.json \
            -g typescript-axios \
            -o documents-client \
            --skip-validate-spec \
            --additional-properties=supportsES6=true,npmName=@nestbox-ai/documents,npmVersion=1.0.${{ github.run_number }},repositoryUrl=https://github.com/NestboxAI/nestbox-ai-clients.git

      - name: Commit and Push Generated Client
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add admin-client
          git add documents-client
          git commit -m "Automatically generated API client from OpenAPI spec [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Admin Dependencies and Build
        run: |
          cd admin-client  # assuming your client is in this directory
          npm install
          npm run build  # ensure "build" script exists in package.json

      - name: Install Documents Dependencies and Build
        run: |
          cd documents-client  # assuming your client is in this directory
          npm install
          npm run build  # ensure "build" script exists in package.json

      - name: Publish Admin Client to npm
        run: |
          cd admin-client
          npm publish --access public --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Documents Client to npm
        run: |
          cd documents-client
          npm publish --access public --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

